language: c

sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gfortran-7
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 90
  - sudo apt install git
  - sudo git clone https://github.com/Reference-LAPACK/lapack.git
  # - pushd lapack && make && sudo make install && popd
  - pushd lapack
  - sudo mkdir build
  - pushd build
  - sudo cmake -DCMAKE_INSTALL_LIBDIR=$HOME/.local/lapack ..
  - sudo cmake --build -j . --target install
  - popd
  - popd
  # - sudo git clone https://github.com/jchristopherson/ferror.git
  # - pushd ferror && ./configure --prefix=/usr && make && sudo make install && popd

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
