language: c

# sudo: required

# before_install:
#   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#   - sudo apt-get update -qq

# install:
#   - sudo apt-get install -qq gfortran-5
#   - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 90
  


compiler: gcc
sudo: require
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - gfortran-6
      - cmake

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script:
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - ln -s /usr/bin/gfortran-6 /usr/local/bin/gfortran
  - gcc -v && gfortran -v && camke --version


script: make
