language: c

sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gfortran-7
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 90
  - sudo apt install git
  - sudo git clone https://github.com/jchristopherson/ferror.git
  - sudo cd ferror && ./configure --prefix=/usr && make && sudo make install
  - sudo git clone https://github.com/Reference-LAPACK/lapack.git
  - sudo cd lapack && ./configure --prefix=/usr && make && sudo make install
  # - sudo wget https://github.com/jchristopherson/ferror/archive/1.3.0.tar.gz
  # - sudo tar -xzvf ferror-1.3.0.tar.gz
  # - sudo pushpd ferror-1.3.0 && ./configure --prefix=/usr && make && sudo make install && popd
  # - sudo wget https://github.com/Reference-LAPACK/lapack/archive/3.9.0.tar.gz
  # - sudo tar -xzvf lapack-3.9.0.tar.gz
  # - sudo pushpd lapack-3.9.0 && ./configure --prefix=/usr && make && sudo make install && popd

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
