name = "linalg"
version = "1.7.3"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2017-2023, Jason Christopherson"
description = "A linear algebra library that provides a user-friendly interface to several BLAS and LAPACK routines."
homepage = "https://github.com/jchristopherson/linalg"

[library]
source-dir = "src"

[dependencies]
ferror = { git = "https://github.com/jchristopherson/ferror" }

[dev-dependencies]
fortran_test_helper = { git = "https://github.com/jchristopherson/fortran_test_helper" }


[install]
library = true

[build]
link = ["blas", "lapack"]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "linalg_test"
source-dir = "tests"
main = "linalg_test.f90"